### ISSUE TITLE
Can't install as a user without sudo access on Linux

### ISSUE THREAD

**Issue by WickedShell** [dronecan/gui_tool#5]
Attempting to install as a user with pip results in an error do to trying to put icons in `/usr/share`

Logs:
``` bash
[wickedshell@lackey ~]$ pip install --user git+https://github.com/DroneCAN/gui_tool@master
Collecting git+https://github.com/DroneCAN/gui_tool@master
  Cloning https://github.com/DroneCAN/gui_tool (to revision master) to /tmp/pip-req-build-d0kuhy4e
  Running command git clone -q https://github.com/DroneCAN/gui_tool /tmp/pip-req-build-d0kuhy4e
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-d0kuhy4e/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-d0kuhy4e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-x_l7_pdv
         cwd: /tmp/pip-req-build-d0kuhy4e/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-d0kuhy4e/setup.py", line 123, in <module>
        shutil.copy(ICON_HIRES, icon_installation_path)
      File "/usr/lib/python3.10/shutil.py", line 417, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
        with open(dst, 'wb') as fdst:
    PermissionError: [Errno 13] Permission denied: '/usr/share/icons/hicolor/256x256/apps/dronecan_gui_tool.png'
    Permanently installing icon to: /usr/share/icons/hicolor/256x256/apps/dronecan_gui_tool.png
    ----------------------------------------
WARNING: Discarding git+https://github.com/DroneCAN/gui_tool@master. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[wickedshell@lackey ~]$ pip --version
pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by davidbuzz** [comment]
readme already specifies using sudo as part of the install process, i don't think its a bug to require sudo at that point.  PR's welcome to allow non-sudo installs.  :-)
